### ISSUE TITLE
extension is working on 1.9.0.0 but not on 1.9.1.0

### ISSUE THREAD

**Issue by EmPeWe** [tzyganu/UMC1.9#86] opened 2015-04-24 09:36 UTC
Hi Marius,

first of all, I want to say thx. I've used your extension a couple of times and it's really awesome!

In my last project, I've discovered, that it's not working in the latest CE version (1.9.1.0), the backend is kind of messed up. In 1.9.0.0 it just works fine and everything is ok and good looking. I didn't test your extension on 1.9.0.1

Are you aware of that?

It's no big deal, as I'm using a standalone plain magento anyway just for creating modules and install them in the intended target system afterwards. Modules created with UMC on 1.9.0.0 are working perfectly on 1.9.1.0

**Comment by tzyganu** [comment] 2015-04-24 09:47
@EmPeWe  What do you mean it's messed up. Can you explain a little or post a screenshot?

**Comment by teknology** [comment] 2015-04-24 12:49
I'm using it on 1.9.1 fine.

**Comment by tzyganu** [comment] 2015-04-28 12:42
I will close this for now since it cannot be reproduced. If you provide some screenshots and steps to reproduce it I will gladly reopen and fix it.

**Closed by tzyganu** 2015-04-28 12:42 UTC

**Comment by EmPeWe** [comment] 2015-05-05 08:57
Thx for your reply.

I couldn't investigate the problem earlier, but now I've found my error. I've installed it with modman but forgot to allow symlinks.

Sorry for the false alarm
