### ISSUE TITLE
attr type "File" cant see/delete uploaded files

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [tzyganu/UMC1.9#87] opened 2015-05-03 16:59 UTC
i created module with entity type flat
and created field with type File

file uploads, and is stored in media dir, list works,
but i can't see uploaded files anywere while editing i can upload new file and that's all

**Comment by tzyganu** [comment] 2015-05-04 06:28
@marcin-derlukiewicz  When editing you entity you should see a filename and a link below the upload input.  
If you don't see it, you either did not upload any file or for some reason the file was not uploaded (too big maybe). Also check in your table to see if the column that corresponds to the file input has a value.

**Comment by tzyganu** [comment] 2015-06-12 07:35
I'm closing this as cannot reproduce it and there was not response from the OP in more than 1 month.

**Closed by tzyganu** 2015-06-12 07:35 UTC
